<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>doc2md</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReverseMarkdown" Version="4.6.0" />
  </ItemGroup>
</Project>
